kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
spec:
  storageClassName: portworx-io-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi