apiVersion: couchbase.com/v2
kind: CouchbaseBackupRestore
metadata:
  name: my-restore
  labels:
    cluster: my-cluster
spec:
  backup: my-backup
  repo: cb-example-perf-2020-03-18T20_05_10
  start:
    int: 1
  end:
    int: 1
  backOffLimit: 2
  logRetention: 24h