---
- hosts: kv:index:n1ql:analytics
  vars:
    couchbase_home: /opt/couchbase
    data_dir: /data
    index_dir: /index
  tasks:
  - name: killing the processes
    shell: 'killall -I -g -q -s SIGKILL {{item}} || true'
    with_items:
      - epmd
      - beam.smp
      - cbq-engine
      - cbft
      - couch_view_index_updater
      - goport
      - goxdcr
      - java
      - indexer
      - memcached
      - moxi
      - mongod
      - mongos
      - mysqld
      - sync_gateway
      - amc
      - asd

  - name: uninstalling the database packages
    yum: state=absent name={{item}}
    with_items:
      - 'couchbase*'
      - 'mongodb*'
      - 'MariaDB*'
      - 'aerospike-server-community*'
      - 'aerospike-tools*'
      - 'aerospike-prometheus-exporter*'
      - 'aerospike-amc-enterprise*'

  - name: removing Couchbase Server files
    file: path={{ couchbase_home }} state=absent

  - name: removing the files remaining in the "{{ data_dir }}" directory
    shell: rm -fr {{ data_dir }}/*
    args:
      warn: no

  - stat: path={{ index_dir }}
    register: index

  - name: removing the files remaining in the "{{ index_dir }}" directory
    shell: rm -fr {{ index_dir }}/*
    when: index.stat.exists
    args:
      warn: no

  - name: removing MySQL installation (if any)
    shell: rm -fr /var/lib/mysql
    args:
      warn: no

  - name: removing Aerospike files and folders
    file: path={{ item }} state=absent
    with_items:
      - /var/run/amc.pid
      - /etc/init.d/aerospike
      - /etc/init.d/amc
      - /etc/logrotate.d/aerospike
      - /usr/bin/aql
      - /usr/bin/asadm
      - /usr/bin/asbackup
      - /usr/bin/asgraphite
      - /usr/bin/asinfo
      - /usr/bin/asloglatency
      - /usr/bin/asrestore
      - /usr/bin/asd
      - /usr/bin/asfixownership
      - /usr/bin/asmigrate2to3
      - /usr/bin/asbenchmark
      - /usr/bin/asloader
      - /usr/bin/asvalidation
      - /usr/bin/asd-coldstart
      - /usr/bin/asd-systemd-helper
      - /etc/aerospike
      - /etc/amc
      - /etc/aerospike-prometheus-exporter
      - /opt/aerospike
      - /opt/amc
      - /var/log/aerospike
      - /var/log/amc
      - /var/log/amc.log
      - /var/run/aerospike
      - /root/aerospike.tgz
      - /root/aerospike-amc-enterprise.rpm